INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test1',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test2',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test3',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test4',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test5',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test6',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test7',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test8',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test9',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test10',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test11',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test12',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test13',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test14',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test15',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test16',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test17',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test18',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test19',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test20',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test21',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test22',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test23',NULL,NULL,'');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test12 2 roberto',20.0,'test 2 roberto','');
INSERT INTO Products (Name,Price,Description,MeasureUnit) VALUES ('test22 2 roberto',20.0,'test 2 roberto','');